### ISSUE TITLE
Panic in dmsghttp tests MacOS

### ISSUE THREAD

**Issue by jdknives** [skycoin/dmsg#128]
Happened in https://ci.appveyor.com/project/jdknives/dmsg/builds/41451303/job/t701w9adxtnuv4s2
```
--- FAIL: ExampleMakeHTTPTransport (0.81s)
coverage: 76.9% of statements
panic: Get "http://0345a78ab861be4fb9c4b3b4283a231a4fbba49a8a673a0f1906eca6db00ed9927:80/": stream closed [recovered]
	panic: Get "http://0345a78ab861be4fb9c4b3b4283a231a4fbba49a8a673a0f1906eca6db00ed9927:80/": stream closed
goroutine 1 [running]:
testing.(*InternalExample).processRunResult(0xc000323b00, {0x0, 0x0}, 0x15f2240, 0x0, {0x16225a0, 0xc00037a570})
	/Users/appveyor/.gvm/gos/go1.17/src/testing/example.go:91 +0x608
testing.runExample.func2()
	/Users/appveyor/.gvm/gos/go1.17/src/testing/run_example.go:60 +0x1a5
panic({0x16225a0, 0xc00037a570})
	/Users/appveyor/.gvm/gos/go1.17/src/runtime/panic.go:1047 +0x266
github.com/skycoin/dmsg/dmsghttp_test.ExampleMakeHTTPTransport()
	/Users/appveyor/projects/dmsg/dmsghttp/examples_test.go:94 +0x12db
testing.runExample({{0x168d637, 0x18}, 0x16a7160, {0x169bb8b, 0x36}, 0x0})
	/Users/appveyor/.gvm/gos/go1.17/src/testing/run_example.go:64 +0x3e4
testing.runExamples(0xc000323e28, {0x1ad4220, 0x1, 0x1})
	/Users/appveyor/.gvm/gos/go1.17/src/testing/example.go:44 +0x27a
testing.(*M).Run(0xc00007e100)
	/Users/appveyor/.gvm/gos/go1.17/src/testing/testing.go:1505 +0xa5d
main.main()
	_testmain.go:95 +0x325
FAIL	github.com/skycoin/dmsg/dmsghttp
```

**Comment by mrpalide** [comment]
Test multiple time, and not happened anymore. Seems after commit [#4feab7f](https://github.com/skycoin/dmsg/commit/4feab7f) by Erson everything is OK now.
