### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ersonp** [skycoin/dmsg#64]
**Describe the bug**
While Following the dmsgget example at https://github.com/skycoin/dmsg/blob/master/docs/dmsgget.md and running the dmsg http server, the bug terminates the program with an error.

**Environment information:**

- OS: Ubuntu Linux
- Platform: Linux 5.8.0-48-generic x86_64

**Steps to Reproduce**

1. Install dmsgget
2. Run ```./bin/dmsg-discovery -t```
3. Run ```./bin/dmsg-server ./integration/configs/dmsgserver1.json``` on a different terminal
2. Run ```go run ./examples/dmsgget/gen-keys/gen-keys.go``` to Generate public/private key pair on a different terminall
3. Run ```go run ./examples/dmsgget/dmsg-example-http-server/dmsg-example-http-server.go --dir /tmp/dmsghttp --sk private key / SK goes here --disc http://localhost:8080``` on the same one
4. See the error

**Actual behavior**
dmsg-example-http-server.go
```
[2021-04-13T15:40:19+05:30] DEBUG disc.NewHTTP [disc]: Created HTTP client. addr="http://localhost:9090"
[2021-04-13T15:40:19+05:30] INFO [dmsg_client]: Discovering dmsg servers...
[2021-04-13T15:40:19+05:30] INFO [dmsg_client]: Dialing session... remote_pk=035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282
[2021-04-13T15:40:19+05:30] INFO [dmsg_client]: Stopped serving client!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7ffe0f]

goroutine 37 [running]:
github.com/skycoin/dmsg.(*EntityCommon).updateClientEntry(0xc0000ea018, 0x978d58, 0xc0000a4240, 0xc0000c3680, 0x0, 0x0)
	/home/erson/Workspace/Go/dmsg/entity_common.go:241 +0x4af
github.com/skycoin/dmsg.NewClient.func1(0x978d58, 0xc0000a4240, 0x1, 0xc00015ec10, 0x98c65ef87df27d00)
	/home/erson/Workspace/Go/dmsg/client.go:110 +0x57
github.com/skycoin/dmsg.(*EntityCommon).setSession(0xc0000ea018, 0x978d58, 0xc0000a4240, 0xc0001a1600, 0xc1df709c6155900)
	/home/erson/Workspace/Go/dmsg/entity_common.go:110 +0x1e5
github.com/skycoin/dmsg.(*Client).dialSession(0xc0000ea000, 0x978d58, 0xc0000a4240, 0xc0001fc460, 0x0, 0x0, 0x0, 0x0)
	/home/erson/Workspace/Go/dmsg/client.go:382 +0x425
github.com/skycoin/dmsg.(*Client).ensureSession(0xc0000ea000, 0x978d58, 0xc0000a4240, 0xc0001fc460, 0x0, 0x0)
	/home/erson/Workspace/Go/dmsg/client.go:349 +0x145
github.com/skycoin/dmsg.(*Client).Serve(0xc0000ea000, 0x978d90, 0xc000112000)
	/home/erson/Workspace/Go/dmsg/client.go:193 +0x1c8
created by main.main
	/home/erson/Workspace/Go/dmsg/examples/dmsgget/dmsg-example-http-server/dmsg-example-http-server.go:54 +0x2ac
exit status 2
```
local discovery
```
Version "4e25fc9" built on "2021-04-13T07:14:11Z" against commit "4e25fc9ad26cf99d2f3d74fc7f18a3b65231a73a"
[2021-04-13T15:39:59+05:30] INFO [dmsg_disc]: Starting
[2021-04-13T15:39:59+05:30] INFO [dmsg_disc]: Serving discovery API... addr=":9090"
2021/04/13 15:40:03 [erson-69/3SHBqz8A2N-000001] "GET http://localhost:9090/dmsg-discovery/entry/035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282 HTTP/1.1" from 127.0.0.1:38518 - 200 350B in 436.894µs
2021/04/13 15:40:03 [erson-69/3SHBqz8A2N-000002] "POST http://localhost:9090/dmsg-discovery/entry/?timeout=true HTTP/1.1" from 127.0.0.1:38518 - 200 50B in 828.438µs
2021/04/13 15:40:11 [erson-69/3SHBqz8A2N-000003] "GET http://localhost:9090/dmsg-discovery/entry/0297347088626e5d6468bc0ed258f2a5e7a279fae48b3636275220611c2eb01321 HTTP/1.1" from 127.0.0.1:38532 - 200 350B in 352.563µs
2021/04/13 15:40:11 [erson-69/3SHBqz8A2N-000004] "POST http://localhost:9090/dmsg-discovery/entry/?timeout=true HTTP/1.1" from 127.0.0.1:38532 - 200 50B in 1.116243ms
2021/04/13 15:40:18 [erson-69/3SHBqz8A2N-000005] "GET http://localhost:9090/dmsg-discovery/entry/035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282 HTTP/1.1" from 127.0.0.1:38546 - 200 350B in 406.26µs
2021/04/13 15:40:18 [erson-69/3SHBqz8A2N-000006] "POST http://localhost:9090/dmsg-discovery/entry/?timeout=true HTTP/1.1" from 127.0.0.1:38546 - 200 50B in 1.002846ms
2021/04/13 15:40:19 [erson-69/3SHBqz8A2N-000007] "GET http://localhost:9090/dmsg-discovery/available_servers HTTP/1.1" from 127.0.0.1:38548 - 200 703B in 389.222µs
2021/04/13 15:40:19 [erson-69/3SHBqz8A2N-000008] "GET http://localhost:9090/dmsg-discovery/entry/035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282 HTTP/1.1" from 127.0.0.1:38548 - 200 350B in 169.727µs
2021/04/13 15:40:19 [erson-69/3SHBqz8A2N-000009] "GET http://localhost:9090/dmsg-discovery/entry/035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282 HTTP/1.1" from 127.0.0.1:38552 - 200 350B in 228.545µs
2021/04/13 15:40:19 [erson-69/3SHBqz8A2N-000010] "POST http://localhost:9090/dmsg-discovery/entry/?timeout=true HTTP/1.1" from 127.0.0.1:38552 - 200 50B in 1.025023ms
2021/04/13 15:40:19 [erson-69/3SHBqz8A2N-000011] "GET http://localhost:9090/dmsg-discovery/entry/035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282 HTTP/1.1" from 127.0.0.1:38554 - 200 349B in 247.995µs
2021/04/13 15:40:19 [erson-69/3SHBqz8A2N-000012] "POST http://localhost:9090/dmsg-discovery/entry/?timeout=true HTTP/1.1" from 127.0.0.1:38554 - 200 50B in 851.968µs
2021/04/13 15:40:26 [erson-69/3SHBqz8A2N-000013] "GET http://localhost:9090/dmsg-discovery/entry/0297347088626e5d6468bc0ed258f2a5e7a279fae48b3636275220611c2eb01321 HTTP/1.1" from 127.0.0.1:38568 - 200 350B in 584.364µs
2021/04/13 15:40:26 [erson-69/3SHBqz8A2N-000014] "POST http://localhost:9090/dmsg-discovery/entry/?timeout=true HTTP/1.1" from 127.0.0.1:38568 - 200 50B in 1.855059ms
2021/04/13 15:40:34 [erson-69/3SHBqz8A2N-000015] "GET http://localhost:9090/dmsg-discovery/entry/035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282 HTTP/1.1" from 127.0.0.1:38582 - 200 350B in 375.061µs
2021/04/13 15:40:34 [erson-69/3SHBqz8A2N-000016] "POST http://localhost:9090/dmsg-discovery/entry/?timeout=true HTTP/1.1" from 127.0.0.1:38582 - 200 50B in 1.120305ms
2021/04/13 15:40:41 [erson-69/3SHBqz8A2N-000017] "GET http://localhost:9090/dmsg-discovery/entry/0297347088626e5d6468bc0ed258f2a5e7a279fae48b3636275220611c2eb01321 HTTP/1.1" from 127.0.0.1:38596 - 200 350B in 400.064µs
2021/04/13 15:40:41 [erson-69/3SHBqz8A2N-000018] "POST http://localhost:9090/dmsg-discovery/entry/?timeout=true HTTP/1.1" from 127.0.0.1:38596 - 200 50B in 961.846µs
2021/04/13 15:40:49 [erson-69/3SHBqz8A2N-000019] "GET http://localhost:9090/dmsg-discovery/entry/035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282 HTTP/1.1" from 127.0.0.1:38610 - 200 350B in 270.072µs
2021/04/13 15:40:49 [erson-69/3SHBqz8A2N-000020] "POST http://localhost:9090/dmsg-discovery/entry/?timeout=true HTTP/1.1" from 127.0.0.1:38610 - 200 50B in 1.042392ms
2021/04/13 15:40:56 [erson-69/3SHBqz8A2N-000021] "GET http://localhost:9090/dmsg-discovery/entry/0297347088626e5d6468bc0ed258f2a5e7a279fae48b3636275220611c2eb01321 HTTP/1.1" from 127.0.0.1:38622 - 200 350B in 255.501µs
2021/04/13 15:40:56 [erson-69/3SHBqz8A2N-000022] "POST http://localhost:9090/dmsg-discovery/entry/?timeout=true HTTP/1.1" from 127.0.0.1:38622 - 200 50B in 892.127µs
2021/04/13 15:41:04 [erson-69/3SHBqz8A2N-000023] "GET http://localhost:9090/dmsg-discovery/entry/035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282 HTTP/1.1" from 127.0.0.1:38636 - 200 350B in 446.433µs
2021/04/13 15:41:04 [erson-69/3SHBqz8A2N-000024] "POST http://localhost:9090/dmsg-discovery/entry/?timeout=true HTTP/1.1" from 127.0.0.1:38636 - 200 50B in 1.903326ms
2021/04/13 15:41:11 [erson-69/3SHBqz8A2N-000025] "GET http://localhost:9090/dmsg-discovery/entry/0297347088626e5d6468bc0ed258f2a5e7a279fae48b3636275220611c2eb01321 HTTP/1.1" from 127.0.0.1:38648 - 200 350B in 430.88µs
2021/04/13 15:41:11 [erson-69/3SHBqz8A2N-000026] "POST http://localhost:9090/dmsg-discovery/entry/?timeout=true HTTP/1.1" from 127.0.0.1:38648 - 200 50B in 1.660693ms
^C[2021-04-13T15:41:14+05:30] INFO [dmsg_disc]: Closing with received signal. signal=interrupt
[2021-04-13T15:41:14+05:30] INFO [dmsg_disc]: Stopping
```

local server
```
Version "4e25fc9" built on "2021-04-13T07:14:11Z" against commit "4e25fc9ad26cf99d2f3d74fc7f18a3b65231a73a"
[2021-04-13T15:40:03+05:30] INFO [dmsg_srv]: Starting
[2021-04-13T15:40:03+05:30] INFO [dmsg_srv]: Read config: {
    "public_key": "035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282",
    "secret_key": "6eddf9399b14f29a60e6a652b321d082f9ed2f0172e02c9d9c1a2a22acf4bee3",
    "discovery": "http://localhost:9090",
    "local_address": ":8081",
    "public_address": "127.0.0.1:8081",
    "max_sessions": 10,
    "update_interval": 0,
    "log_level": "info"
}
[2021-04-13T15:40:03+05:30] DEBUG disc.NewHTTP [disc]: Created HTTP client. addr="http://localhost:9090"
[2021-04-13T15:40:03+05:30] INFO [dmsg_srv]: Serving server. advertised_addr="127.0.0.1:8081" local_pk=035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282
[2021-04-13T15:40:03+05:30] DEBUG [dmsg_srv]: Updating entry.
[2021-04-13T15:40:03+05:30] INFO [dmsg_srv]: Accepting sessions... advertised_addr="127.0.0.1:8081" local_pk=035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282
[2021-04-13T15:40:18+05:30] DEBUG [dmsg_srv]: Updating entry.
[2021-04-13T15:40:19+05:30] INFO [dmsg_srv]: Started session. remote_pk=035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282 remote_tcp=127.0.0.1:46192
[2021-04-13T15:40:19+05:30] DEBUG [dmsg_srv]: Updating entry. available_sessions=9
[2021-04-13T15:40:19+05:30] INFO [dmsg_srv]: Stopping session... error="EOF" session=035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282
[2021-04-13T15:40:19+05:30] DEBUG [dmsg_srv]: Updating entry. available_sessions=10
[2021-04-13T15:40:19+05:30] INFO [dmsg_srv]: Stopped session. error=<nil> remote_pk=035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282 remote_tcp=127.0.0.1:46192
[2021-04-13T15:40:34+05:30] DEBUG [dmsg_srv]: Updating entry.
[2021-04-13T15:40:49+05:30] DEBUG [dmsg_srv]: Updating entry.
[2021-04-13T15:41:04+05:30] DEBUG [dmsg_srv]: Updating entry.
```

**Expected behavior**
Start without an error.

**Additional context**
This is replicated on the local environment but the same error is seen when using ```dmsg.discovery.skywire.cc``` as the discovery.

**Comment by ersonp** [comment]
After some inspection, I've found that the Entry object returned from [here](https://github.com/skycoin/dmsg/blob/e7066b2098c5c246c9e025fa581aab09af92de72/entity_common.go#L231) contains server instead of client 
```
{
	"version": "0.0.1",
	"sequence": 4439,
	"timestamp": 1618321866986409700,
	"static": "035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282",
	"server": {
		"address": "dmsg.server0.skywire.cc:30080",
		"availableSessions": 509
	},
	"signature": "b49f46f4d4fba81a504abf0ae2e93a4fb74cff9dc5063360849037979966f75576ddc29181fca998a2e2f424a41226454fda6b7a4be1f07fd85e01456f5c525600"
}
```
so the when [entry.Client.DelegatedServers](https://github.com/skycoin/dmsg/blob/e7066b2098c5c246c9e025fa581aab09af92de72/entity_common.go#L241) is called it throws an error

**Comment by ersonp** [comment]
A clean install later the entry object received is now the correct one. Not sure what caused this issue.


> After some inspection, I've found that the Entry object returned from [here](https://github.com/skycoin/dmsg/blob/e7066b2098c5c246c9e025fa581aab09af92de72/entity_common.go#L231) contains server instead of client
> 
> ```
> {
> 	"version": "0.0.1",
> 	"sequence": 4439,
> 	"timestamp": 1618321866986409700,
> 	"static": "035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282",
> 	"server": {
> 		"address": "dmsg.server0.skywire.cc:30080",
> 		"availableSessions": 509
> 	},
> 	"signature": "b49f46f4d4fba81a504abf0ae2e93a4fb74cff9dc5063360849037979966f75576ddc29181fca998a2e2f424a41226454fda6b7a4be1f07fd85e01456f5c525600"
> }
> ```
> 
> so the when [entry.Client.DelegatedServers](https://github.com/skycoin/dmsg/blob/e7066b2098c5c246c9e025fa581aab09af92de72/entity_common.go#L241) is called it throws an error
